module.exports = [
  'Aardvark',
  'Aardwolf',
  'Abyssinian',
  'Addax',
  'Affenpinscher',
  'Afghan Hound',
  'African Bush Elephant',
  'African Civet',
  'African Forest Elephant',
  'African Palm Civet',
  'African Wild Dog',
  'Aidi',
  'Ainu',
  'Airedale Terrier',
  'Airedoodle',
  'Akbash',
  'Akita',
  'Akita Shepherd',
  'Alabai',
  'Alaskan Husky',
  'Alaskan Klee Kai',
  'Alaskan Malamute',
  'Alaskan Shepherd',
  'Alpaca',
  'Alpine Dachsbracke',
  'Alpine Goat',
  'Alusky',
  'Amazon River Dolphin (Pink Dolphin)',
  'American Alsatian',
  'American Bulldog',
  'American Cocker Spaniel',
  'American Coonhound',
  'American Eskimo Dog',
  'American Foxhound',
  'American Hairless Terrier',
  'American Leopard Hound',
  'American Pit Bull Terrier',
  'American Pygmy Goat',
  'American Staffordshire Terrier',
  'American Water Spaniel',
  'Amur Leopard',
  'Anatolian Shepherd Dog',
  'Angora Ferret',
  'Angora Goat',
  'Anteater',
  'Antelope',
  'Ape',
  'Appenzeller Dog',
  'Apple Head Chihuahua',
  'Arctic Fox',
  'Arctic Hare',
  'Arctic Wolf',
  'Armadillo',
  'Asian Elephant',
  'Asian Palm Civet',
  'Asiatic Black Bear',
  'Aurochs',
  'Aussiedoodle',
  'Aussiedor',
  'Australian Bulldog',
  'Australian Cattle Dog',
  'Australian Kelpie Dog',
  'Australian Labradoodle',
  'Australian Mist',
  'Australian Retriever',
  'Australian Shepherd',
  'Australian Terrier',
  'Axolotl',
  'Aye Aye',
  'Babirusa',
  'Baboon',
  'Bactrian Camel',
  'Badger',
  'Baleen Whale',
  'Balinese',
  'Balkan Lynx',
  'Banded Palm Civet',
  'Bandicoot',
  'Barbet',
  'Basenji Dog',
  'Bassador',
  'Basset Fauve de Bretagne',
  'Basset Hound',
  'Bassetoodle',
  'Bat',
  'Bavarian Mountain Hound',
  'Bea-Tzu',
  'Beabull',
  'Beagador',
  'Beagle',
  'Beagle Shepherd',
  'Beaglier',
  'Beago',
  'Bear',
  'Bearded Collie',
  'Beaski',
  'Beauceron',
  'Beaver',
  'Bedlington Terrier',
  'Beefalo',
  'Belgian Shepherd',
  'Belgian Tervuren',
  'Bengal Tiger',
  'Bergamasco',
  'Berger Picard',
  'Bernedoodle',
  'Bernese Mountain Dog',
  'Bernese Shepherd',
  'Bichon Frise',
  'Bichpoo',
  'Biewer Terrier',
  'Bighorn Sheep',
  'Bilby',
  'Binturong',
  'Birman',
  'Bison',
  'Black And Tan Coonhound',
  'Black Rhinoceros',
  'Black Russian Terrier',
  'Black-Footed Ferret',
  'Bloodhound',
  'Blue Lacy Dog',
  'Blue Picardy Spaniel',
  'Blue Whale',
  'Bluetick Coonhound',
  'Bobcat',
  'Boggle',
  'Boglen Terrier',
  'Bolognese Dog',
  'Bombay',
  'Bongo',
  'Bonobo',
  'Borador',
  'Border Collie',
  'Border Terrier',
  'Bordoodle',
  'Borkie',
  'Bornean Orang-utan',
  'Borneo Elephant',
  'Boston Terrier',
  'Bottlenose Dolphin',
  'Bouvier Des Flandres',
  'Bowhead Whale',
  'Boxador',
  'Boxer Dog',
  'Boxerdoodle',
  'Boxsky',
  'Boxweiler',
  'Boykin Spaniel',
  'Brazilian Terrier',
  'British Timber',
  'Brittany',
  'Brown Bear',
  'Brown Hyena',
  'Brug',
  'Brussels Griffon',
  'Buffalo',
  'Bull Shark',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  'Burmese',
  'Bush Baby',
  'Cactus Mouse',
  'Cairn Terrier',
  'Camel',
  'Canaan Dog',
  'Canada Lynx',
  'Canadian Eskimo Dog',
  'Canadian Horse',
  'Cane Corso',
  'Cape Lion',
  'Capybara',
  'Caracal',
  'Caribou',
  'Carolina Dog',
  'Cashmere Goat',
  'Cat',
  'Catahoula Leopard',
  'Catalan Sheepdog',
  'Cava Tzu',
  'Cavador',
  'Cavalier King Charles Spaniel',
  'Cavapoo',
  'Cesky Fousek',
  'Cesky Terrier',
  'Chameleon',
  'Chamois',
  'Chartreux',
  'Cheagle',
  'Cheetah',
  'Chesapeake Bay Retriever',
  'Chihuahua',
  'Chimpanzee',
  'Chinchilla',
  'Chinese Crested Dog',
  'Chinese Shar-Pei',
  'Chinook',
  'Chipmunk',
  'Chipoo',
  'Chiweenie',
  'Chorkie',
  'Chow Chow',
  'Chow Shepherd',
  'Cinnamon Ferret',
  'Clouded Leopard',
  'Clumber Spaniel',
  'Coati',
  'Cockalier',
  'Cockapoo',
  'Cocker Spaniel',
  'Collared Peccary',
  'Collie',
  'Common Toad',
  'Corgidor',
  'Corgipoo',
  'Corkie',
  'Corman Shepherd',
  'Corn Rex Cat (Cornish Rex)',
  'Coton de Tulear',
  'Cotton-top Tamarin',
  'Cougar',
  'Cow',
  'Coyote',
  'Crab-Eating Macaque',
  'Crabeater Seal',
  'Cross Fox',
  'Cross River Gorilla',
  'Curly Coated Retriever',
  'Cuscus',
  'Czechoslovakian Wolfdog',
  'Dachsador',
  'Dachshund',
  'Dalmadoodle',
  'Dalmador',
  'Dalmatian',
  'Dapple Dachshund',
  'Darwin’s fox',
  'Deer',
  'Deer Head Chihuahua',
  'Deutsche Bracke',
  'Devon Rex',
  'Dhole',
  'Dik-Dik',
  'Dingo',
  'Doberman Pinscher',
  'Dog',
  'Dogo Argentino',
  'Dogue De Bordeaux',
  'Dolphin',
  'Donkey',
  'Dorgi',
  'Dorkie',
  'Dormouse',
  'Double Doodle',
  'Douc',
  'Doxiepoo',
  'Doxle',
  'Drever',
  'Dugong',
  'Dunker',
  'Dusky Dolphin',
  'Dwarf Hamster',
  'Eastern Barred Bandicoot',
  'Eastern Chipmunk',
  'Eastern Gorilla',
  'Eastern Lowland Gorilla',
  'Echidna',
  'Egyptian Mau',
  'Eland',
  'Elephant',
  'Elephant Seal',
  'Elephant Shrew',
  'Elk',
  'Emperor Tamarin',
  'English Bulldog',
  'English Cocker Spaniel',
  'English Cream Golden Retriever',
  'English Foxhound',
  'English Pointer',
  'English Setter',
  'English Shepherd',
  'English Springer Spaniel',
  'Entlebucher Mountain Dog',
  'Epagneul Pont Audemer',
  'Ermine',
  'Eskimo Dog',
  'Eskipoo',
  'Estrela Mountain Dog',
  'Eurasian Beaver',
  'Eurasian Lynx',
  'Eurasian Wolf',
  'European Polecat',
  'European Wildcat',
  'Evening Bat',
  'Fallow deer',
  'False Killer Whale',
  'Feist',
  'Fennec Fox',
  'Ferret',
  'Field Spaniel',
  'Fila Brasileiro',
  'Fin Whale',
  'Finnish Spitz',
  'Fisher Cat',
  'Fishing Cat',
  'Flat-Coated Retriever',
  'Florida Panther',
  'Flying Lemur',
  'Flying Squirrel',
  'Formosan Mountain Dog',
  'Fossa',
  'Fox',
  'Fox Squirrel',
  'Fox Terrier',
  'French Bulldog',
  'Frenchton',
  'Frengle',
  'Fruit Bat',
  'Fur Seal',
  'Gazelle',
  'Genet',
  'Geoffroys Tamarin',
  'Gerberian Shepsky',
  'Gerbil',
  'German Pinscher',
  'German Shepherd Guide',
  'German Sheppit',
  'German Sheprador',
  'German Shorthaired Pointer',
  'German Spitz',
  'Giant Armadillo',
  'Giant Panda Bear',
  'Giant Schnauzer',
  'Giant Schnoodle',
  'Gibbon',
  'Giraffe',
  'Glechon',
  'Glen Of Imaal Terrier',
  'Goat',
  'Goberian',
  'Goldador',
  'Golden Dox',
  'Golden Lion Tamarin',
  'Golden Newfie',
  'Golden Pyrenees',
  'Golden Retriever',
  'Golden Saint',
  'Golden Shepherd',
  'Golden-Crowned Flying Fox',
  'Goldendoodle',
  'Gopher',
  'Gordon Setter',
  'Gorilla',
  'Grasshopper Mouse',
  'Gray Fox',
  'Great Dane',
  'Great Danoodle',
  'Great Pyrenees',
  'Greater Swiss Mountain Dog',
  'Greenland Dog',
  'Grey Mouse Lemur',
  'Grey Seal',
  'Greyhound',
  'Griffonshire',
  'Grizzly Bear',
  'Groenendael',
  'Guinea Pig',
  'Hamster',
  'Harbor Seal',
  'Hare',
  'Harp Seal',
  'Harrier',
  'Havanese',
  'Havapoo',
  'Havashire',
  'Hawaiian Monk Seal',
  'Hedgehog',
  'Highland Cattle',
  'Himalayan',
  'Hippopotamus',
  'Hoary Bat',
  'Hokkaido',
  'Honduran White Bat',
  'Honey Badger',
  'Hooded Seal',
  'Horgi',
  'Horse',
  'Howler Monkey',
  'Human',
  'Huntaway',
  'Huskador',
  'Huskita',
  'Husky',
  'Husky Jack',
  'Huskydoodle',
  'Hyena',
  'Ibex',
  'Ibizan Hound',
  'Icelandic Sheepdog',
  'Impala',
  'Indian Elephant',
  'Indian Giant Squirrel',
  'Indian Palm Squirrel',
  'Indian Rhinoceros',
  'Indochinese Tiger',
  'Indri',
  'Irish Doodle',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish WolfHound',
  'Italian Greyhound',
  'Jack Russell',
  'Jackabee',
  'Jackal',
  'Jackrabbit',
  'Jaguar',
  'Jaguarundi Cat',
  'Japanese Chin',
  'Japanese Macaque',
  'Japanese Spitz',
  'Japanese Squirrel',
  'Japanese Terrier',
  'Javan Rhinoceros',
  'Javanese',
  'Jerboa',
  'Kai Ken',
  'Kangal',
  'Kangaroo',
  'Kangaroo Rat',
  'Kerry Blue Terrier',
  'Key Deer',
  'Kiko Goat',
  'Killer Whale',
  'Kinder Goat',
  'King Shepherd',
  'Kinkajou',
  'Kishu',
  'Kit Fox',
  'Koala',
  'Kodkod',
  'Kooikerhondje',
  'Koolie',
  'Kudu',
  'Kuvasz',
  'Labahoula',
  'Labmaraner',
  'Labradane',
  'Labradoodle',
  'Labrador Retriever',
  'Labraheeler',
  'Lakeland Terrier',
  'LaMancha Goat',
  'Lancashire Heeler',
  'Lapponian Herder',
  'Lemming',
  'Lemur',
  'Leonberger',
  'Leopard',
  'Leopard Cat',
  'Leopard Seal',
  'Lhasa Apso',
  'Lhasapoo',
  'Liger',
  'Lion',
  'Little Brown Bat',
  'Llama',
  'Long-Haired Rottweiler',
  'Lowchen',
  'Lynx',
  'Macaque',
  'Mackenzie Wolf',
  'Maine Coon',
  'Malayan Civet',
  'Malayan Tiger',
  'Malteagle',
  'Maltese',
  'Maltese Shih Tzu',
  'Maltipoo',
  'Manatee',
  'Manchester Terrier',
  'Mandrill',
  'Maned Wolf',
  'Marble Fox',
  'Markhor',
  'Marmoset',
  'Marmot',
  'Masked Palm Civet',
  'Mastador',
  'Mastiff',
  'Meagle',
  'Meerkat',
  'Mexican Free-Tailed Bat',
  'Miki',
  'Mini Labradoodle',
  'Miniature Bull Terrier',
  'Miniature Pinscher',
  'Mink',
  'Minke Whale',
  'Mole',
  'Mongoose',
  'Mongrel',
  'Monkey',
  'Moorhen',
  'Moose',
  'Morkie',
  'Moscow Watchdog',
  'Mountain Cur',
  'Mountain Feist',
  'Mountain Gorilla',
  'Mountain Lion',
  'Mouse',
  'Mudi',
  'Mule',
  'Muntjac',
  'Muskox',
  'Muskrat',
  'Naked Mole Rat',
  'Narwhal',
  'Neanderthal',
  'Neapolitan Mastiff',
  'Nebelung',
  'Newfoundland',
  'Newfypoo',
  'Nigerian Goat',
  'Nilgai',
  'Norfolk Terrier',
  'North American Black Bear',
  'Northern Fur Seal',
  'Northern Inuit Dog',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Forest',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Nubian Goat',
  'Numbat',
  'Nyala',
  'Ocelot',
  'Okapi',
  'Old English Sheepdog',
  'Olive Baboon',
  'Opossum',
  'Orang-utan',
  'Otter',
  'Otterhound',
  'Ox',
  'Pademelon',
  'Pangolin',
  'Panther',
  'Papillon',
  'Parson Russell Terrier',
  'Patas Monkey',
  'Patterdale Terrier',
  'Peagle',
  'Peekapoo',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Pere Davids Deer',
  'Perro De Presa Canario',
  'Persian',
  'Peruvian Inca Orchid',
  'Petit Basset Griffon Vendéen',
  'Petite Goldendoodle',
  'Pheasant',
  'Pied Tamarin',
  'Pig',
  'Pika',
  'Pine Marten',
  'Pink Fairy Armadillo',
  'Pit Bull',
  'Pitador',
  'Pitsky',
  'Platypus',
  'Pocket Beagle',
  'Pocket Pitbull',
  'Pointer',
  'Polar Bear',
  'Polish Lowland Sheepdog',
  'Pomapoo',
  'Pomchi',
  'Pomeagle',
  'Pomeranian',
  'Pomsky',
  'Poochon',
  'Poodle',
  'Poogle',
  'Porcupine',
  'Porpoise',
  'Possum',
  'Potoroo',
  'Prairie Dog',
  'Proboscis Monkey',
  'Pronghorn',
  'Pudelpointer',
  'Pug',
  'Pugapoo',
  'Puggle',
  'Pugshire',
  'Puma',
  'Pumi',
  'Pygmy Hippopotamus',
  'Pygmy Marmoset (Finger Monkey)',
  'Pygora Goat',
  'Pyrador',
  'Pyredoodle',
  'Quagga',
  'Quokka',
  'Quoll',
  'Rabbit',
  'Raccoon',
  'Raccoon Dog',
  'Ragamuffin',
  'Ragdoll',
  'Raggle',
  'Rat',
  'Rat Terrier',
  'Red Fox',
  'Red Panda',
  'Red Squirrel',
  'Red Wolf',
  'Red-handed Tamarin',
  'Redbone Coonhound',
  'Reindeer',
  'Rhinoceros',
  'River Otter',
  'Rock Hyrax',
  'Rodents',
  'Roe Deer',
  'Rottsky',
  'Rottweiler',
  'Russell Terrier',
  'Russian Bear Dog',
  'Russian Blue',
  'Saanen Goat',
  'Saarloos Wolfdog',
  'Saber-Toothed Tiger',
  'Sable',
  'Sable Black German Shepherd',
  'Sable Ferret',
  'Saiga',
  'Saint Berdoodle',
  'Saint Bernard',
  'Saint Shepherd',
  'Saluki',
  'Sambar',
  'Samoyed',
  'Saola',
  'Savanna Goat',
  'Schipperke',
  'Schneagle',
  'Schnoodle',
  'Scimitar-horned Oryx',
  'Scottish Terrier',
  'Sea Lion',
  'Sea Otter',
  'Seal',
  'Sealyham Terrier',
  'Sei Whale',
  'Serval',
  'Sheep',
  'Sheepadoodle',
  'Shepadoodle',
  'Shepkita',
  'Shepweiler',
  'Shiba Inu',
  'Shih Poo',
  'Shih Tzu',
  'Shollie',
  'Shrew',
  'Siamese',
  'Siberian',
  'Siberian Husky',
  'Siberian Ibex',
  'Siberian Retriever',
  'Siberian Tiger',
  'Siberpoo',
  'Silky Terrier',
  'Silver Labrador',
  'Skunk',
  'Skye Terrier',
  'Sloth',
  'Smooth Fox Terrier',
  'Snorkie',
  'Snow Leopard',
  'Snowshoe',
  'Snowshoe Hare',
  'Somali',
  'South China Tiger',
  'Spanador',
  'Spanish Goat',
  'Spanish Mastiff',
  'Spectacled Bear',
  'Sperm Whale',
  'Spider Monkey',
  'Spinone Italiano',
  'Springbok',
  'Springerdoodle',
  'Squirrel',
  'Squirrel Monkey',
  'Sri Lankan Elephant',
  'Stabyhoun',
  'Staffordshire Bull Terrier',
  'Standard Schnauzer',
  'Star-nosed mole',
  'Steller’s Sea Cow',
  'Stoat',
  'Striped Hyena',
  'Sugar Glider',
  'Sumatran Elephant',
  'Sumatran Orang-utan',
  'Sumatran Rhinoceros',
  'Sumatran Tiger',
  'Sun Bear',
  'Swedish Vallhund',
  'Syrian Hamster',
  'Taco Terrier',
  'Takin',
  'Tamaskan',
  'Tapanuli Orang-utan',
  'Tapir',
  'Tarsier',
  'Tasmanian Devil',
  'Tasmanian Tiger',
  'Teddy Bear Hamster',
  'Teddy Roosevelt Terrier',
  'Tennessee Walking Horse',
  'Tenterfield Terrier',
  'Terrier',
  'Texas Heeler',
  'Thai Ridgeback',
  'Tibetan Fox',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Tiffany',
  'Tiger',
  'Torkie',
  'Toy Fox Terrier',
  'Toy Poodle',
  'Transylvanian Hound',
  'Tree Kangaroo',
  'Treeing Tennessee Brindle',
  'Treeing Walker Coonhound',
  'Tuatara',
  'Turkish Angora',
  'Uakari',
  'Uinta Ground Squirrel',
  'Unau (Linnaeus’s Two-Toed Sloth)',
  'Utonagan',
  'Vampire Bat',
  'Vaquita',
  'Vervet Monkey',
  'Vicuña',
  'Vizsla',
  'Volpino Italiano',
  'Wallaby',
  'Walrus',
  'Warthog',
  'Water Buffalo',
  'Water Vole',
  'Weasel',
  'Weimaraner',
  'Weimardoodle',
  'Welsh Corgi',
  'Welsh Terrier',
  'West Highland Terrier',
  'Western Gorilla',
  'Western Lowland Gorilla',
  'Westiepoo',
  'Wheaten Terrier',
  'Whippet',
  'White Ferret / Albino Ferrets',
  'White Rhinoceros',
  'White Tiger',
  'White-Faced Capuchin',
  'White-tail deer',
  'Whoodle',
  'Wild Boar',
  'Wildebeest',
  'Wire Fox Terrier',
  'Wirehaired Pointing Griffon',
  'Wolf',
  'Wolverine',
  'Wombat',
  'Wood Bison',
  'Woodrat',
  'Woolly Mammoth',
  'Woolly Monkey',
  'Xerus',
  'Xoloitzcuintli',
  'Yak',
  'Yakutian Laika',
  'Yoranian',
  'Yorkie Bichon',
  'Yorkie-poo',
  'Yorkshire Terrier',
  'Zebra',
  'Zebu',
  'Zonkey',
  'Zorse',
  'Zuchon'
];